
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'tasty_bytes'
version: '1.4.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
    "dbt_date:time_zone": "Etc/UTC"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  tasty_bytes:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +schema: harmonized
    intermediate:
      +schema: harmonized
    marts:
      +schema: analytics
    ml:
      materialized: table
      +schema: ml
      +snowflake_warehouse: "TASTY_SNOWPARK_WH"
      model_inference:
        +docs:
          node_color: "red"
      model_training:
        +pre_hook: ["CREATE STAGE IF NOT EXISTS forecast_stage"]
        +docs:
          node_color: "#cc5801"
      training_base:
        +docs:
          node_color: "orange"
